### ISSUE TITLE
json object of URL code

### ISSUE THREAD

**Issue by Uafinder** [tuzzmaniandevil/kademi-url-shortener#10]
When you using GetByCode method it returns a number of parameters. However, two things:
1. WebsideID is returning in some kind of digital format, not a usual WebsideID. Is it ok?
![image](https://cloud.githubusercontent.com/assets/1945230/10029842/f3bc657a-617c-11e5-9d86-36f9d7c06e13.png)

2. If Notes field contains too much symbols, it crops a whole string and doesn't return websideid.
![image](https://cloud.githubusercontent.com/assets/1945230/10029819/d11a0d2e-617c-11e5-9957-1c85fcf2cdeb.png)

**Comment by tuzzmaniandevil** [comment]
**1.** That should be fine for now, I'll create an issue to enhance the data returned

**2.** If you look at the email source code you will see it contains all the data :-) Some of it was just interpreted as HTML code.
![nimbus-image-1442956947324](https://cloud.githubusercontent.com/assets/3378330/10032040/ac20c730-61d4-11e5-965e-41b53b8cc1fd.png)

**Comment by tuzzmaniandevil** [comment]
**1.** See #11

**Comment by Uafinder** [comment]
Ok, thanks.
I've commented the 11-th
