### ISSUE TITLE
Review the json data being returned by the API

### ISSUE THREAD

**Issue by tuzzmaniandevil** [tuzzmaniandevil/kademi-url-shortener#11]
This should include the website name not ID, and possibly also some statitics like the amount of clicks

**Comment by tuzzmaniandevil** [comment]
I have removed the websiteId and addedd the amount of clicks:
```
{
  "code": "RLScin",
  "url": "http://google.com",
  "jobName": "urlJob_test-job",
  "jobTitle": "Test Job",
  "notes": "",
  "clicks": 15
}
```

**Comment by Uafinder** [comment]
Check it today. Looks like the old thing.
![image](https://cloud.githubusercontent.com/assets/1945230/10056079/4ed1ab12-6242-11e5-839f-10ac91d7d9ae.png)

**Comment by tuzzmaniandevil** [comment]
Sorri I forgot to update the test app. Please try again.

**Comment by Uafinder** [comment]
yup, all works ok!
