### ISSUE TITLE
Let users specify a user name/email when generating a short code from the admin

### ISSUE THREAD

**Issue by tuzzmaniandevil** [tuzzmaniandevil/kademi-url-shortener#14]
That user will then be passed to the expression to allow codes to be generated for other users.

**Comment by tuzzmaniandevil** [comment]
@Uafinder Please test.

**Comment by Uafinder** [comment]
Problems:
1. Username or email field size is restricted on 20 symbols. Should be increased.
2. Username or email field are searching users by userid, not username. Should be on username.
3. When trying to create a short code got an error:
![image](https://cloud.githubusercontent.com/assets/1945230/10084929/8961ec66-630e-11e5-988a-038f0ea821e7.png)
No matter with or not short code specified

**Comment by tuzzmaniandevil** [comment]
**1.** I've removed the field size limit
**2.** I've change the text of the popup to say "User id" instead of "User name".
![userid](https://cloud.githubusercontent.com/assets/3378330/10087847/af880eaa-636a-11e5-8eb2-d1e1b53a049f.png)
**3.** This should be working correctly now.

**Comment by tuzzmaniandevil** [comment]
I have removed this feature.
