### ISSUE TITLE
Change getShortLinkWithDomain/getShortLink API to autogenerate a short URL job if one doesn't exists and create a short url

### ISSUE THREAD

**Issue by tuzzmaniandevil** [tuzzmaniandevil/kademi-url-shortener#16]
This API will allow a user to specify the following parameters:
- **WebsiteRootFolder/CommonResource** - _Required_
- **Job Name** - _Required_
- **Long URL** - _Optional_
- **Expression** - _Optional_
- **User** - _Optional_

This will either find a job with that name and generate a short code or if a job doesn't exists create the job, will in the URL and Expression fields then create a short code.

**Comment by tuzzmaniandevil** [comment]
Please note, the new API looks like this:
`getShortLinkWithDomain(page, jobName, url, expr, user)`

I have updated the READEME file to reflect the change.

**Comment by tuzzmaniandevil** [comment]
@Uafinder Please Test

**Comment by tuzzmaniandevil** [comment]
@Uafinder Can this issue be close?

**Comment by Uafinder** [comment]
I'm working on it

**Comment by Uafinder** [comment]
1. Short contruction like "@{applications.shortUrlTest.call('getShortLinkWithDomain', website, 'doesntuselongcontruction', user)" creates an empty job anyway. For see it, you could use any name in this construction and watch that job will be created. It forms a link which leads to error 404 Null page.

2. I've used a long contruction for creating a job, but get incorrect address error.
@{applications.shortUrlTest.call('getShortLinkWithDomain', website, 'longcontruction', user, 'http://kademi.co', '@{job.url + website.getLoginToken(user)}')
![image](https://cloud.githubusercontent.com/assets/1945230/10230651/f8b5afb2-6886-11e5-9055-845ab11fab0c.png)

Both constructions are there: http://apptest.admin.kademi-beta.co/groupEmails/111333/#messages-tab

3. A lot of mistackes in readme file. Not sure if it's vital for you, just FYI
![image](https://cloud.githubusercontent.com/assets/1945230/10230688/44c0e0d4-6887-11e5-8a74-e936edd4af25.png)
copy-paste

![image](https://cloud.githubusercontent.com/assets/1945230/10230751/83e07f36-6887-11e5-8b8a-2bd95a976055.png)
bracket by mistake

**Comment by tuzzmaniandevil** [comment]
I have corrected the examples, the URL should be 'http://kademi.co?'

**Comment by Uafinder** [comment]
Yup, everything looks work ok!

one thing left:
Short contruction like "@{applications.shortUrlTest.call('getShortLinkWithDomain', website, 'doesntuselongconstruction3', user)" creates an empty job anyway. For see it, you could use any name in this construction and watch that job will be created. It forms a link which leads to error 404 Null page.
