### ISSUE TITLE
When adding new short code click counter stucks

### ISSUE THREAD

**Issue by Uafinder** [tuzzmaniandevil/kademi-url-shortener#21]
![image](https://cloud.githubusercontent.com/assets/1945230/10173098/3bb29bce-66eb-11e5-9196-f435f2c94d24.png)

Steps to reproduce:
1. Go to url http://apptest.admin.olhub.com/shortUrl/
2. Add some short code
3. Watch that counters are stuck

**Comment by tuzzmaniandevil** [comment]
This has been corrected.

**Comment by Uafinder** [comment]
looks ok!
