### ISSUE TITLE
Application settings doesn't saving

### ISSUE THREAD

**Issue by Uafinder** [tuzzmaniandevil/kademi-url-shortener#5]
1. Go here
http://apptest.admin.kademi-beta.co/manageApps/
2. Go to settings of the URL Shorterer App
3. Enter a valid username or email
4. Push save
5. Refresh page
6. Go to the settings of the URL Shorterer App again and watch the empty field.
I've no idea either it doesn't visible or it doesn't save at all.

**Comment by tuzzmaniandevil** [comment]
This is related to this issue https://github.com/Kademi/kademi-dev/issues/760
I have correct this now

**Comment by Uafinder** [comment]
Looks ok!
