### ISSUE TITLE
Anonymous user field should check on existed users while saving

### ISSUE THREAD

**Issue by Uafinder** [tuzzmaniandevil/kademi-url-shortener#6]
For example:
http://apptest.admin.kademi-beta.co/manageApps/
1. Go to the URL shorteter app settings
2. Enter invalid username or email (or anything else)
3. Push save
4. It should warn you that there no such user existed in that org.

**Comment by tuzzmaniandevil** [comment]
Good suggestion!

**Comment by tuzzmaniandevil** [comment]
Done

**Comment by Uafinder** [comment]
Works ok!
