### ISSUE TITLE
Error while generating email

### ISSUE THREAD

**Issue by Uafinder** [tuzzmaniandevil/kademi-url-shortener#8]
looks like Mvel exception. Or it could be my mistake.
The error description is: [Error: [Error: unknown class or illegal statement: org.mvel2.ParserContext@12e92ed4] [Near : {... pptestsp

This one emal body
Hello user, look at this awesome blog! @{
website = organisation.find('/websites/apptestsp/').current;
applications.shortUrl.call('getShortLinkWithDomain', '123', website, user) }

http://apptest.admin.kademi-beta.co/shortUrl/123/#details-tab
http://apptest.admin.kademi-beta.co/groupEmails/111333/#messages-tab
http://apptest.admin.kademi-beta.co/blogs/blog/123/

**Comment by tuzzmaniandevil** [comment]
This was caused by styling been added to the expression, expressions should be added using the text editor not the html editor.
Also the app id being used was incorrect, for this org shortUrlTest should be used instead of shortUrl
eg. application.shortUrlTest.call()

**Comment by Uafinder** [comment]
Yup, looks ok at this point
