### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by Uafinder** [tuzzmaniandevil/kademi-url-shortener#9]
question1:
Should technical account (for using as anonymous user) have some permissions, group memberships and other stuff?

question2:
when system generates a user token, should it use a tech account? because it tries to use my currecnt account. Is this correct?
http://apptestsp.kademi-beta.co/blogs/blog/newBlog?miltonUserUrl=/users/vgfinderteam&miltonUserUrlHash=dd055959-ca14-4e63-aba2-a525964c2a16:gX5KOKKFhJEl4n_QDXWSr2wtPV0

question3:
I've setup everything like in the example, but when i'm trying to access a short link, it gives me a bad page error.
Am i setup it correctly?
http://apptest.admin.kademi-beta.co/shortUrl/123/#details-tab
http://apptest.admin.kademi-beta.co/blogs/
![image](https://cloud.githubusercontent.com/assets/1945230/10029023/755b3c3c-6178-11e5-9ff3-b77aed115059.png)

**Comment by tuzzmaniandevil** [comment]
**Q1**: The user should just be in a group in the organisation, no permissions or roles are needed.

**Q2**: When you generate a short link from the admin it will make "user" the current logged in user, when generated from an email,SMS or html template "user" will be the user that was passed into the method

**Q3**: The url is redirecting correctly, but http://apptestsp.kademi-beta.co/blogs/blog/newBlog doesn't exist, http://apptestsp.kademi-beta.co/blogs/blog/123 does exists though, see short URL TestingTheCode

**Comment by Uafinder** [comment]
q1 - thanks
q3 - oops, my mistake, thanks

q2 - understood, thanks
however can't make an idea how to send email to non-Kademi user, for use a tech account.
When i tried to send a test, it asks a template account and then using it as a token.
SMS are not setup for this org so can't check them too.
Could you give an advice? Thanks

**Comment by tuzzmaniandevil** [comment]
The anon account is used when a person goes to the short link, that's the only time the anon account is used. So when someone goes to http://version1.apptestsp.kademi-beta.co/OJW0O4 the anon account is used to create a record in the json database

**Comment by Uafinder** [comment]
ok, maybe i can't understand something.
look here.
we have this link (it was created automatically when email was send)
http://version1.apptestsp.kademi-beta.co/IZsHTk
it leads us to article2
we give this link to some user, he click on it and ... he enters to the site under my account and can do anything he wants.
Am i correct? Or i just can't get something?

**Comment by tuzzmaniandevil** [comment]
If you generate the link from the admin screen then yes that is correct, but i'm adding a feature to fix this, see #14

**Comment by Uafinder** [comment]
ok, understood, thanks
